[platformio]
; Descomente a linha abaixo para compilar apenas o tasmota32-sensors
default_envs = tasmota32-sensors

[env:tasmota32-sensors]
extends = env:tasmota32_base
build_flags = ${env:tasmota32_base.build_flags}
              -DUSE_SCRIPT
